### ISSUE TITLE
Why not bump schemaVersion on existing manifest?

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/wg-reference-types#66]
Please see conversation here https://github.com/opencontainers/wg-reference-types/pull/59#discussion_r918388398

**Comment by jdolitsky** [comment]
cc @rchincha @jonjohnsonjr  @sudo-bmitch

**Comment by sudo-bmitch** [comment]
Since the original usage of the field specifies:

> The value of this field will not change. This field MAY be removed in a future version of the specification.

I think it would be unexpected for us to bump this field. What value is there in bumping the schemaVersion and not bumping a version in the mediaType? Wouldn't it be more appropriate for us to remove the schemaVersion field in the artifact-spec and depend entirely on the mediaType since there would be no prior use of the field and the spec indicates it can be removed?

**Comment by rchincha** [comment]
From what I understand, the following are the requirements:
1) the community should be able to evolve the spec as they see fit (use cases, limitations, etc)
2) some field(s) should always be available such that tools can parse it to be forward-compatible for rejection at least

If there will always be a mediaType to select on at least to achieve 2), then that works also. Selecting on `schemaVersion` would have been a self-explanatory IMO, but bikeshedding.

**Comment by sudo-bmitch** [comment]
I believe we can add new fields anywhere in the spec without needing to change any version number or media type. That gives the forward compatibility where new implementations handle additional fields when they are defined while older implementations should ignore (or pass through when storing) unknown fields.

The point where we want to change the media type is when the updated content can no longer be used by existing implementations (e.g. when the artifact spec deleted the config descriptor from the image media type).

**Comment by rchincha** [comment]
So the conclusion here:

1) ** deprecation**: Drop/deprecate `schemaVersion` in the image spec on some next spec release

2) **never-upgrade**: For folks who don't want to move past `schemaVersion <= 2`, use the version encoded in the mediaType as a selector to reject updates

3) **selectively-upgrade**: For folks who want to move past `schemaVersion = 2` but could potentially be behind latest spec versions in the wild, basically follow [Protocol Buffers guidelines](https://developers.google.com/protocol-buffers/docs/overview#updating-defs) for forward-compatibility

4) **always-upgrade**: Others, keep their code/support in sync with latest spec version

**Comment by sudo-bmitch** [comment]
I believe schemaVersion is in the never-upgrade with a possible future deprecation category.

**Comment by rchincha** [comment]
So the conclusion here:

1) **future-deprecation**: Drop/deprecate `schemaVersion` in the image spec on some next spec release

2) **never-upgrade**: For folks who don't want to move past `schemaVersion <= 2`, use the version encoded in the mediaType as a selector to reject updates. The field `schemaVersion` itself is not very useful and marked for future deprecation.

3) **selectively-upgrade**: For folks who want to move past `schemaVersion = 2` but could potentially be behind latest spec versions in the wild, basically follow [Protocol Buffers guidelines](https://developers.google.com/protocol-buffers/docs/overview#updating-defs) for forward-compatibility

4) **always-upgrade**: Others, keep their code/support in sync with latest spec version

**Comment by sudo-bmitch** [comment]
We've settled on deleting the `schemaVersion` from the new artifact manifest definition.
