### ISSUE TITLE
Prop E artifact annotations questions

### ISSUE THREAD

**Issue by Jamstah** [opencontainers/wg-reference-types#71]
> **Annotations**
> These annotations would be added for artifacts:
> - org.opencontainers.artifact.type: type of artifact (sig, sbom, etc)
> - org.opencontainers.artifact.description: human readable description for the artifact
> - org.opencontainers.artifact.created: creation time for a manifest

Are these annotations *required* for the new artifact type?

Are these annotations *valid* to use on an image manifest?

**Comment by sudo-bmitch** [comment]
The spec would be updated to define the annotations. Individual artifacts may use them, and I think we would push for an artifact should specify a type, but I stopped short of saying an artifact must use any of these annotations.

**Comment by jdolitsky** [comment]
Closing as PRs are open in upstream repos
