### ISSUE TITLE
[Vote] Allow for server-side filtering using artifactType

### ISSUE THREAD

**Issue by michaelb990** [opencontainers/wg-reference-types#78]
Following up with adding filtering for artifactType, now that we have it as a standalone field (#59).

I've opened #74 and would like to propose a vote for the community to voice their opinion on this proposal. Vote by giving a 👍 to either of the comments below.

**Comment by michaelb990** [comment]
Yes, add optional server-side filtering on artifactType to the spec.

**Comment by michaelb990** [comment]
No, do not add server-side filtering, rely on client-side filtering alone.

**Comment by sudo-bmitch** [comment]
Mine is a weak "no". There's not much value add for me given that clients must still implement client side filtering, and I worry it will complicate servers. If others find it useful, then don't let my vote hold this back.

**Comment by jdolitsky** [comment]
Mine is a "yes" given the fact that it is optional to implement

**Comment by sudo-bmitch** [comment]
With the 5:1 vote, and my 1 being a weak no, I've merged this. Thanks to everyone for voting and to @michaelb990 for putting this one together.
