### ISSUE TITLE
Archive this repository?

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/wg-reference-types#79]
As discussed on the call, since upstream PRs have been opened (almost), does it make sense to archive this repo? Any changes to the proposal that deviate from the original proposal E can take place in the PRs

**Comment by sudo-bmitch** [comment]
I'd lean towards leaving it open until the PRs are reviewed by OCI and merged, just in case they have a "back to the drawing board" level of change request. Hopefully that doesn't happen, and if we did archive, we could always reopen the repo if needed.
