### ISSUE TITLE
Nominate yourself as maintainer

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/wg-reference-types#8]
With great power comes great responsibility

**Comment by jdolitsky** [comment]
I nominate myself

**Comment by sudo-bmitch** [comment]
I nominate myself

**Comment by nishakm** [comment]
I nominate myself :D

**Comment by SteveLasker** [comment]
I nominate myself

**Comment by imjasonh** [comment]
I omnomnominate myself 😋

**Comment by lachie83** [comment]
I suggest following the code owners format in Github documented [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners). We should create a team called wg-reference-types-maintainers that we reference in the code owners file using `@opencontainers/wg-reference-types-maintainers`

**Comment by lachie83** [comment]
We should also add the handles [here](https://github.com/opencontainers/wg-reference-types#organizers) from the WG organizers.

**Comment by jdolitsky** [comment]
thanks everyone. lets do this thang
