### ISSUE TITLE
Can we define the behaviour for a missing reference?

### ISSUE THREAD

**Issue by Jamstah** [opencontainers/wg-reference-types#80]
There is nothing in the spec that says what registries need to do if you put in an artifact (I'm thinking about image indexes) that refers to a manifest that doesn't exist within the repository.

The options seem to be:
1. Registry refuses the artifact
2. Registry accepts the artifact, responds correctly to a call to the references API even if there is no manifest stored for the referenced digest

I'd like it if this spec were to make a call, even if that call is to write down that "The registry can decide the behaviour and both are valid options".

For garbage collection we do say this, but I'm really talking about tagged references:
> For registries that implement garbage collection based on tagged manifests, an untagged manifest with a refers field pointing to an existing manifest should not be removed. When a manifest is deleted by a garbage collection policy or by an API request, all untagged artifacts that referred to that manifest may be cleaned by garbage collection.

**Comment by Jamstah** [comment]
I'm aware this may be too late, or that this might need to be raised elsewhere now, so feel free to say that!

**Comment by sudo-bmitch** [comment]
For a `refers` field to a manifest that doesn't exist, the call we made was that the registry MAY return an empty list before that reference exists, but once the reference exists, the referrers API MUST include previously pushed entries. That lets us, for example, push a signature before pushing the image. This wording is going in the next PR to the oci-playground/distribution-spec.

**Comment by sudo-bmitch** [comment]
See https://github.com/oci-playground/distribution-spec/pull/11 in spec.md under Listing Referrers:

> If `<ref>` does not exist, a registry MAY return an empty manifest list.
> After `<ref>` is pushed, the registry MUST include previously pushed entries in the manifest list.

**Comment by Jamstah** [comment]
Thanks, just went and had a look on the playground.

What I didn't find was any guidance on what the registry is allowed to do when someone attempts to upload an artifact that points to a digest that doesn't exist. Has that been discussed too?

**Comment by sudo-bmitch** [comment]
Good point, I'm adding this to the PR:
https://github.com/oci-playground/distribution-spec/pull/11/files#diff-bc6661da34ecae62fbe724bb93fd69b91a7f81143f2683a81163231de7e3b545R204

> A registry SHOULD accept a manifest with a `refers` field that references a manifest that does not exist.

**Comment by Jamstah** [comment]
That works for me, mainly because I'm thinking about image indexes and that weak references should be a supported thing, also because I think being able to push a graph of references in parallel makes sense.

Going to tag @milosgajdos and @deleteriousEffect because we had a similar discussion a while ago.

**Comment by sudo-bmitch** [comment]
This is in the PR to distribution-spec, so I'll mark this as closed over here, but feel free to keep the discussion going.
