### ISSUE TITLE
Create governance.md

### ISSUE THREAD

**Issue by nishakm** [opencontainers/wg-reference-types#9]
Issue from WG meeting on Feb 8 2022: document our process for decision making and next steps.

**Comment by jdolitsky** [comment]
@nishakm - do you wanna take a stab at this? I don't think it needs to be super heavyweight

**Comment by sudo-bmitch** [comment]
Will be resolved by #11.

**Comment by sudo-bmitch** [comment]
@nishakm are we good to close this one?
